SEARCH_RES_PAP = {u'_embedded':
                    {u'annonce': 
                        [
                        {u'_embedded': 
                            {u'consultation': [
                                    {
                                        u'_links': {
                                          u'self': {
                                          u'href': u'https://ws.pap.fr/immobilier/~/favoris/426202030/consultation'
                                          }
                                        },
                                    u'action': None,
                                    u'mes_favoris': False}
                                ],
                             u'photo': [{u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62A2030.thumb.jpg'}},
                                 u'ordre': 1}],
                             u'place': [{
                                 u'_links': {u'self': {u'href': u'https://ws.pap.fr/gis/places/37780'}},
                                 u'id': 37780,
                                 u'is_idf': True,
                                 u'lat': 48.831902,
                                 u'lng': 2.35585,
                                 u'slug': u'paris-13e',
                                 u'title': u'Paris 13e'}]
                             },
                         u'_links': {u'desktop': {u'href': u'https://www.pap.fr/annonce/vente-immobiliere-paris-13e-g37780-a-partir-du-2-pieces-jusqu-a-320000-euros-r426202030'},
                               u'self': {u'href': u'https://ws.pap.fr/immobilier/annonces/426202030'}},
                         u'a_la_une': u'0',
                         u'id': 426202030,
                         u'marker': {u'lat': u'48.820270',
                               u'lng': u'2.364572'},
                         u'nb_chambres_max': 1,
                         u'nb_photos': 6,
                         u'nb_pieces': 2,
                         u'nouvelle_annonce': False,
                         u'prix': 310000,
                         u'produit': u'vente',
                         u'surface': 43,
                         u'texte_accroche': u'',
                         u'typebien': u'appartement',
                         u'video': None,
                         u'visite_virtuelle': None},
                         {u'_embedded': {u'consultation': [{u'_links': {u'self': {u'href': u'https://ws.pap.fr/immobilier/~/favoris/426202032/consultation'}},
                                          u'action': None,
                                          u'mes_favoris': False}],
                                 u'photo': [{u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62A2032.thumb.jpg'}},
                                       u'ordre': 1}],
                                 u'place': [{u'_links': {u'self': {u'href': u'https://ws.pap.fr/gis/places/37780'}},
                                       u'id': 37780,
                                       u'is_idf': True,
                                       u'lat': 48.831902,
                                       u'lng': 2.35585,
                                       u'slug': u'paris-13e',
                                       u'title': u'Paris 13e'}]},
                         u'_links': {u'desktop': {u'href': u'https://www.pap.fr/annonce/vente-immobiliere-paris-13e-g37780-a-partir-du-2-pieces-jusqu-a-320000-euros-r426202032'},
                               u'self': {u'href': u'https://ws.pap.fr/immobilier/annonces/426202032'}},
                         u'a_la_une': u'0',
                         u'id': 426202032,
                         u'marker': {u'lat': u'48.820270',
                               u'lng': u'2.364572'},
                         u'nb_chambres_max': 1,
                         u'nb_photos': 5,
                         u'nb_pieces': 2,
                         u'nouvelle_annonce': False,
                         u'prix': 310000,
                         u'produit': u'vente',
                         u'surface': 43,
                         u'texte_accroche': u'',
                         u'typebien': u'appartement',
                         u'video': None,
                         u'visite_virtuelle': None}],
            u'place': [{u'_links': {u'self': {u'href': u'https://ws.pap.fr/gis/places/37780'}},
                  u'id': 37780,
                  u'is_idf': True,
                  u'lat': 48.831902,
                  u'lng': 2.35585,
                  u'slug': u'paris-13e',
                  u'title': u'Paris 13e'}]},
     u'_links': {u'canonical': {u'href': u'https://ws.pap.fr/immobilier/annonces?recherche%5Bproduit%5D=vente&recherche%5Bgeo%5D%5Bids%5D%5B0%5D=37780&recherche%5Bprix%5D%5Bmax%5D=320000&recherche%5Bnb_pieces%5D%5Bmin%5D=2&recherche%5Bfavoris%5D=0&order=date-desc&size=200&page=1'},
           u'first': {u'href': u'https://ws.pap.fr/immobilier/annonces?recherche%5Bproduit%5D=vente&recherche%5Bgeo%5D%5Bids%5D%5B0%5D=37780&recherche%5Bprix%5D%5Bmax%5D=320000&recherche%5Bnb_pieces%5D%5Bmin%5D=2&recherche%5Bfavoris%5D=0&order=date-desc&size=200&page=1'},
           u'last': {u'href': u'https://ws.pap.fr/immobilier/annonces?recherche%5Bproduit%5D=vente&recherche%5Bgeo%5D%5Bids%5D%5B0%5D=37780&recherche%5Bprix%5D%5Bmax%5D=320000&recherche%5Bnb_pieces%5D%5Bmin%5D=2&recherche%5Bfavoris%5D=0&order=date-desc&size=200&page=1'},
           u'self': {u'href': u'https://ws.pap.fr/immobilier/annonces?recherche%5Bnb_pieces%5D%5Bmin%5D=2&recherche%5Bproduit%5D=vente&recherche%5Bgeo%5D%5Bids%5D%5B0%5D=37780&recherche%5Bprix%5D%5Bmax%5D=320000&page=1&size=1000'}},
     u'adtech': {u'android': {u'top': u'pap_app_mob_android_resultat_vente-top-5'},
           u'ios': {u'top': u'pap_app_mob_ios_resultat_vente-top-5'},
           u'kvstring': u'departement=75;ville=paris-13e;nb_pieces_min=2;nb_chambres_min=N;prix_max=320000'},
     u'check': 1554370772,
     u'date_consultation': 1554370772,
     u'map': {u'center': {u'lat': None, u'lng': None}, u'zoom': None},
     u'nb_items': 2,
     u'nb_items_overflow': False,
     u'nb_pages': 1,
     u'order': u'date-desc',
     u'page': 1,
     u'page_nb_items': 2,
     u'page_nb_items_geocoded': 2,
     u'recherche': {u'date_consultation': None,
            u'favoris': False,
            u'geo': {u'ids': [37780]},
            u'id': None,
            u'last_check': None,
            u'nb_chambres': {u'max': None, u'min': None},
            u'nb_pieces': {u'max': None, u'min': 2},
            u'prix': {u'max': 320000, u'min': None},
            u'produit': u'vente',
            u'surface': {u'max': None, u'min': None},
            u'surface_terrain': {u'max': None, u'min': None},
            u'tags': [],
            u'transport': {u'ids': []},
            u'typesbien': [],
            u'utilisateurs_id': None},
     u'size': 200}

PAP_AD_DETAIL = {u'_embedded': {u'photo': [{u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62A2030.jpg'}},
                  u'ordre': 1},
                  {u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62B2030.jpg'}},
                  u'ordre': 2},
                  {u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62C2030.jpg'}},
                  u'ordre': 3},
                  {u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62D2030.jpg'}},
                  u'ordre': 4},
                  {u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62E2030.jpg'}},
                  u'ordre': 5},
                  {u'_links': {u'self': {u'href': u'https://static.pap.fr/photos/C62/C62F2030.jpg'}},
                  u'ordre': 6}],
            u'place': [{u'_links': {u'self': {u'href': u'https://ws.pap.fr/gis/places/37780'}},
                  u'id': 37780,
                  u'is_idf': True,
                  u'lat': 48.831902,
                  u'lng': 2.35585,
                  u'slug': u'paris-13e',
                  u'title': u'Paris 13e'}],
            u'transport': [{u'_links': {u'self': {u'href': u'https://ws.pap.fr/gis/transports/689'}},
                    u'id': 689,
                    u'lat': 48.818717,
                    u'lng': 2.360501,
                    u'slug': u'porte-d-italie',
                    u'title': u"Porte d'Italie"},
                    {u'_links': {u'self': {u'href': u'https://ws.pap.fr/gis/transports/690'}},
                    u'id': 690,
                    u'lat': 48.819902,
                    u'lng': 2.364966,
                    u'slug': u'porte-de-choisy',
                    u'title': u'Porte de Choisy'},
                    {u'_links': {u'self': {u'href': u'https://ws.pap.fr/gis/transports/691'}},
                    u'id': 691,
                    u'lat': 48.821357,
                    u'lng': 2.369308,
                    u'slug': u'porte-d-ivry',
                    u'title': u"Porte d'Ivry"}]},
     u'_links': {u'desktop': {u'href': u'https://www.pap.fr/annonces/-r426202030'},
           u'desktop_canonical': {u'href': u'https://www.pap.fr/annonces/-r426202030'},
           u'self': {u'href': u'https://ws.pap.fr/immobilier/annonces/426202030'}},
     u'adtech': {u'android': {u'bottom': u'pap_app_mob_android_detail_vente-bottom-5'},
           u'ios': {u'bottom': u'pap_app_mob_ios_detail_vente-bottom-5'},
           u'kvstring': u'typebien=appartement;departement=75;ville=paris-13e;nb_pieces=2;nb_chambres=1;prix=310000;surface=43;transport=porte-d-italie%3Aporte-de-choisy%3Aporte-d-ivry'},
     u'classe_energie': None,
     u'date_classement': 1553586479,
     u'has_email': False,
     u'id': 426202030,
     u'marker': {u'lat': 48.821137471547, u'lng': 2.3676584246889},
     u'nb_chambres_max': 1,
     u'nb_photos': 6,
     u'nb_pieces': 2,
     u'prix': 310000,
     u'produit': u'vente',
     u'surface': 43,
     u'telephones': [u'00.00.00.00.00'],
     u'texte': u"Appartement de 2 pi\xe8ces, de 43 m\xb2 situ\xe9 \xe0 Porte de Choisy.\r\n\r\nL'appartement est tr\xe8s lumineux, avec une vue d\xe9gag\xe9e sans vis-\xe0-vis, orient\xe9 plein sud. Il est situ\xe9 au 5e \xe9tage avec ascenseur\r\n\r\nCuisine avec plaques de cuisson et de nombreux rangements. La salle de bain poss\xe8de une baignoire et les toilettes sont s\xe9par\xe9es. Grands placards dans la chambre et l'entr\xe9e.\r\n\r\nUne place de parking souterrain et une cave compl\xe8tent ce bien.\r\n\r\nPr\xe9sence d'un gardien dans l'immeuble.\r\n\r\nNombreux transports (m\xe9tro, tramway et bus) et commerces au pied de l'immeuble.\r\n\r\nVisites \xe0 partir du samedi 30 mars.\r\n\r\nAppeler apr\xe8s 12h\r\n\r\nAgences s'abstenir.",
     u'texte_accroche': u'',
     u'texte_contact': u'',
     u'typebien': u'appartement',
     u'video': None,
     u'visite_virtuelle': None},
}
