SEARCH_SELOGER = {u'experts': [{u'city': u'Paris 9\xe8me',
                       u'description': u'Groupe familial depuis 1984',
                       u'directoryId': 146619,
                       u'headline': u'12 agences \xe0 Paris et Neuilly - 1 bien vendu par jour',
                       u'id': 3100,
                       u'inseeCode': u'750110',
                       u'logoUrl': u'https://v.seloger.com/s/width/165/bandeaux/1/1/5/k/115kugkgshpuuwshs1d9yhv5xwmqp2kvcdndrjozm.jpg',
                       u'name': u'JUNOT',
                       u'professionalId': 243081,
                       u'realtyCount': 13,
                       u'thirdPartyId': 270274,
                       u'transactionType': 2,
                       u'type': 1,
                       u'url': u'https://www.seloger.com/professionnels/groupe-familial-depuis-1984/paris-9eme-75/agency-146619.htm',
                       u'zipCode': u'75009'},
                      {u'city': u'Paris 10\xe8me',
                       u'description': u'Agence Immobili\xe8re',
                       u'directoryId': 106642,
                       u'headline': u'Sp\xe9cialiste immobilier \xe0 Paris 10\xe8me.',
                       u'id': 317,
                       u'inseeCode': u'750110',
                       u'logoUrl': u'https://v.seloger.com/s/height/165/bandeaux/1/3/i/y/13iy42zahik2wr8azplmpsozctocu7l97l2qemq56.jpg',
                       u'name': u'HOME SQUARE',
                       u'professionalId': 59206,
                       u'realtyCount': 22,
                       u'thirdPartyId': 60501,
                       u'transactionType': 2,
                       u'type': 1,
                       u'url': u'https://www.seloger.com/professionnels/agence-immobiliere/paris-10eme-75/agency-106642.htm',
                       u'zipCode': u'75010'}],
         u'geolocatedCount': 11,
         u'items': [{u'bedrooms': 1,
                     u'city': u'Paris 10\xe8me',
                     u'id': 145738991,
                     u'isExclusiveness': True,
                     u'isIndividual': False,
                     u'isNew': True,
                     u'isSelection': False,
                     u'level': 1,
                     u'livingArea': 25.49,
                     u'livingAreaUnit': u'm\xb2',
                     u'permalink': u'https://www.seloger.com/annonces/achat/appartement/paris-10eme-75/louis-blanc-aqueduc/145738991.htm?p=',
                     u'photos': [u'https://v.seloger.com/s/width/800/visuels/1/f/v/j/1fvjvbww58zscnf45rbucw73jy711bc6n1aoc1q38.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/y/0/h/1y0h26gluxdonvjjxk2mfv18bdrn5s1c0715g8cpg.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/2/6/1/5/2615zgt53fhyjvko92d2swp6hn50485ua4e2u5mc4.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/h/n/a/0hna00i5kocz640c7nqz0u9ed7vpg1e580021if6c.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/n/1/4/0n14emm1udnwf0u6ml985mo73gmozayrvpzvnpnis.jpg',
                                 u'https://v.seloger.com/s/width/600/visuels/0/r/1/r/0r1r9r8fvyuf270uapsc5m7c2tt8wz7y27zwhdvrx.jpg'],
                     u'polygon': u'',
                     u'price': 249500.0,
                     u'priceAnnuity': 0.0,
                     u'priceUnit': u'\u20ac',
                     u'priceVariation': {u'date': u'0001-01-01T00:00:00',
                                         u'newPrice': 0.0,
                                         u'oldPrice': 0.0,
                                         u'status': 0},
                     u'professional': {u'directoryId': 66479,
                                       u'email': u'contact@nope.com',
                                       u'id': 73906,
                                       u'logoUrl': u'https://v.seloger.com/s/height/75/logos/1/f/1/h/1f1h2vluc6txzkajusbg4rwbm00mivs35sc8konk5.jpg',
                                       u'name': u'AGENCE SAP',
                                       u'phoneNumber': u'000000000',
                                       u'publicationId': 390615,
                                       u'type': 1},
                     u'publicationId': 390615,
                     u'realtyType': 1,
                     u'rooms': 2,
                     u'thirdPartyId': 102753,
                     u'title': u'Appartement',
                     u'transactionType': 2,
                     u'zipCode': u'75010'},
                    {u'bedrooms': 1,
                     u'city': u'Paris 10\xe8me',
                     u'id': 145382317,
                     u'isExclusiveness': False,
                     u'isIndividual': False,
                     u'isNew': False,
                     u'isSelection': False,
                     u'level': 1,
                     u'livingArea': 27.17,
                     u'livingAreaUnit': u'm\xb2',
                     u'permalink': u'https://www.seloger.com/annonces/achat/appartement/paris-10eme-75/chateau-d-eau-lancry/145382317.htm?p=',
                     u'photos': [u'https://v.seloger.com/s/width/800/visuels/0/6/r/n/06rno7bizo90jxtrec0iga03vghrmjdpnjwy1nocg.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/i/d/q/0idqhk8eo4az3txyph0u929cjn3386f4xkel18idc.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/a/s/z/0aszn40ena86wt333gpzlog0mulms54x3hz9hs9hc.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/v/s/y/0vsy4570erxj9s8467l1veb8qecvuofkxiunjl0cg.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/o/x/7/0ox7w3i7c7jdz4il9en35fx7cjv81vvhx2kda9c74.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/y/z/n/0yzndeqmivq10z70qqau2ve2qnyexs84nxzuw0buo.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/c/j/y/1cjygjcpnuxryu0r1r8v36mgne1r34ljwh3zrh3pc.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/o/c/b/0ocbaibqs8o3p3tuy844v8t6blwqo5vsjtheh9w5c.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/d/r/y/1drytxqsy7u8igmb4n96xuwnu3tk3vd1zcvyn5ds0.jpg',
                                 u'https://v.seloger.com/s/height/600/visuels/0/j/b/8/0jb853bv4xr5cz2270wbqv6m0dw8w9xs2c2ggn9z4.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/6/c/f/06cfvyge9z3457w6k38tj46wdibj1991e5p7mmb5s.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/i/7/v/1i7v3y7etefh4egj315uqpazzp5om3bycmbwuwydc.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/f/6/i/0f6i1561jxuwaqhl6xeoxyw55ee1z0p2ne9k3mtxc.jpg'],
                     u'polygon': u'',
                     u'price': 265000.0,
                     u'priceAnnuity': 0.0,
                     u'priceUnit': u'\u20ac',
                     u'priceVariation': {u'date': u'0001-01-01T00:00:00',
                                         u'newPrice': 0.0,
                                         u'oldPrice': 0.0,
                                         u'status': 0},
                     u'professional': {u'directoryId': 56639,
                                       u'email': u'agence10@nope.com',
                                       u'id': 11495,
                                       u'logoUrl': u'https://v.seloger.com/s/width/150/logos/0/0/3/u/003ucsq3agnbeojdeg9l0wsrdut6ywezsioygqxjq.jpg',
                                       u'name': u'PARIS IMMOBILIER',
                                       u'phoneNumber': u'0000000000',
                                       u'publicationId': 19111,
                                       u'type': 1},
                     u'publicationId': 19111,
                     u'realtyType': 1,
                     u'rooms': 2,
                     u'thirdPartyId': 3622,
                     u'title': u'Appartement',
                     u'transactionType': 2,
                     u'zipCode': u'75010'},
                    {u'bedrooms': 1,
                     u'city': u'Paris 10\xe8me',
                     u'id': 145541957,
                     u'isExclusiveness': False,
                     u'isIndividual': False,
                     u'isNew': False,
                     u'isSelection': False,
                     u'level': 1,
                     u'livingArea': 37.24,
                     u'livingAreaUnit': u'm\xb2',
                     u'permalink': u'https://www.seloger.com/annonces/achat/appartement/paris-10eme-75/louis-blanc-aqueduc/145541957.htm?p=',
                     u'photos': [u'https://v.seloger.com/s/width/800/visuels/1/5/d/l/15dl6nfpvi4q45e6h84y12yvyw6hayjpkm2sxc81c.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/k/r/n/0krn4yzbmf1o1ga0mk8nxyxxxau2obsbwln4bdu3r.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/k/q/s/0kqsb3tjdy2bndkmsccadn11j2nj9wjg1a1oz1i28.jpg',
                                 u'https://v.seloger.com/s/width/799/visuels/2/1/1/x/211xk06fcrqadwmmwxgxqjjoio9827tvm491884h8.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/h/u/x/0huxtmljepf04zdkudj6d2souqswuny9af8cm0cds.jpg'],
                     u'polygon': u'',
                     u'price': 280000.0,
                     u'priceAnnuity': 0.0,
                     u'priceUnit': u'\u20ac',
                     u'priceVariation': {u'date': u'0001-01-01T00:00:00',
                                         u'newPrice': 0.0,
                                         u'oldPrice': 0.0,
                                         u'status': 0},
                     u'professional': {u'directoryId': 64833,
                                       u'email': u'contact-encheres@nope.com',
                                       u'id': 66656,
                                       u'logoUrl': u'https://v.seloger.com/s/width/150/logos/0/r/b/b/0rbbr5zjdhtexfvmjm3zsi7qez570dstkrkydz7rj.jpg',
                                       u'name': u'PARIS NOTAIRES SERVICES',
                                       u'phoneNumber': u'000000000000',
                                       u'publicationId': 338376,
                                       u'type': 1},
                     u'publicationId': 338376,
                     u'realtyType': 1,
                     u'rooms': 2,
                     u'thirdPartyId': 84843,
                     u'title': u'Appartement',
                     u'transactionType': 2,
                     u'zipCode': u'75010'},
                    {u'bedrooms': 1,
                     u'city': u'Paris 10\xe8me',
                     u'id': 139377345,
                     u'isExclusiveness': True,
                     u'isIndividual': False,
                     u'isNew': False,
                     u'isSelection': False,
                     u'level': 1,
                     u'livingArea': 30.0,
                     u'livingAreaUnit': u'm\xb2',
                     u'permalink': u'https://www.seloger.com/annonces/achat/appartement/paris-10eme-75/faubourg-du-temple-hopital-saint-louis/139377345.htm?p=',
                     u'photos': [u'https://v.seloger.com/s/width/800/visuels/2/8/e/v/28evk308662mv64rwdv9pprzszs9vf3f0pl9njzo4.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/9/u/m/19umyuvhxp90mr82aa1yir25wxvfk62376blmvo7o.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/8/9/7/0897dn2k1yk3tli4kaqy5d3dbyl58byg4p6ia7u50.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/0/1/p/z/01pzsp9tr7jec6c3cd6nlc5lg1dxfn56ghi5uc1uc.jpg'],
                     u'polygon': u'',
                     u'price': 310000.0,
                     u'priceAnnuity': 0.0,
                     u'priceUnit': u'\u20ac',
                     u'priceVariation': {u'date': u'0001-01-01T00:00:00',
                                         u'newPrice': 0.0,
                                         u'oldPrice': 0.0,
                                         u'status': 0},
                     u'professional': {u'directoryId': 59376,
                                       u'email': u'beauxrepaires-contact@nope.com',
                                       u'id': 41539,
                                       u'logoUrl': u'https://v.seloger.com/s/width/150/logos/0/b/z/8/0bz8dfetmrf1yp1s86qzm297qd430zbjmdllveqmg.jpg',
                                       u'name': u'ERA BEAUX REPAIRES GONCOURT',
                                       u'phoneNumber': u'00000000000',
                                       u'publicationId': 192059,
                                       u'type': 1},
                     u'publicationId': 192059,
                     u'realtyType': 1,
                     u'rooms': 2,
                     u'thirdPartyId': 15767,
                     u'title': u'Appartement',
                     u'transactionType': 2,
                     u'zipCode': u'75010'},
                    {u'bedrooms': 1,
                     u'city': u'Paris 10\xe8me',
                     u'id': 145145585,
                     u'isExclusiveness': False,
                     u'isIndividual': False,
                     u'isNew': False,
                     u'isSelection': False,
                     u'level': 1,
                     u'livingArea': 25.0,
                     u'livingAreaUnit': u'm\xb2',
                     u'permalink': u'https://www.seloger.com/annonces/achat/appartement/paris-10eme-75/faubourg-du-temple-hopital-saint-louis/145145585.htm?p=',
                     u'photos': [u'https://v.seloger.com/s/width/600/visuels/1/z/6/i/1z6ioatzlcjrq5pv8oegkourzfgmgptrzsdo673b4.jpg',
                                 u'https://v.seloger.com/s/width/600/visuels/0/n/k/5/0nk5p4hq4pyp6isgcjbrij5dxgiv5pzs44hdoom80.jpg',
                                 u'https://v.seloger.com/s/height/600/visuels/2/8/t/f/28tfq7svsi612b3ruqya8k896w20kl2vwrmkgz4kg.jpg',
                                 u'https://v.seloger.com/s/width/600/visuels/0/x/r/j/0xrjsj3d49kw43qpch5etqxet8v10alvafcwij88w.jpg',
                                 u'https://v.seloger.com/s/width/600/visuels/0/o/h/g/0ohg9cu43oimrmjchjkpaf3d4noq1fex6pj0lzmo0.jpg',
                                 u'https://v.seloger.com/s/height/600/visuels/0/8/f/z/08fz2nt2ufc8os3dcjeh5fqmauepggimwzwyxggrk.jpg',
                                 u'https://v.seloger.com/s/height/800/visuels/0/r/2/h/0r2hv86itjpfa5dsghl95mg0eut9fj8yi4e8cojeg.jpg',
                                 u'https://v.seloger.com/s/width/600/visuels/1/e/2/f/1e2fk5xqiu17p5jqonerj712pk9le0k88kkkuxtog.jpg'],
                     u'polygon': u'',
                     u'price': 310000.0,
                     u'priceAnnuity': 0.0,
                     u'priceUnit': u'\u20ac',
                     u'priceVariation': {u'date': u'0001-01-01T00:00:00',
                                         u'newPrice': 0.0,
                                         u'oldPrice': 0.0,
                                         u'status': 0},
                     u'professional': {u'directoryId': 60147,
                                       u'email': u'pitimmo75@nope.com',
                                       u'id': 45437,
                                       u'logoUrl': u'https://v.seloger.com/s/width/150/logos/0/e/e/9/0ee9lfjnkoasdnq8nfa694xeamy2y92rhqb056kf3.jpg',
                                       u'name': u'PIT IMMO',
                                       u'phoneNumber': u'0000000000',
                                       u'publicationId': 259149,
                                       u'type': 1},
                     u'publicationId': 259149,
                     u'realtyType': 1,
                     u'rooms': 2,
                     u'thirdPartyId': 3706,
                     u'title': u'Appartement',
                     u'transactionType': 2,
                     u'zipCode': u'75010'},
                    {u'bedrooms': 1,
                     u'city': u'Paris 10\xe8me',
                     u'id': 143940829,
                     u'isExclusiveness': False,
                     u'isIndividual': False,
                     u'isNew': False,
                     u'isSelection': False,
                     u'level': 1,
                     u'livingArea': 28.0,
                     u'livingAreaUnit': u'm\xb2',
                     u'permalink': u'https://www.seloger.com/annonces/achat/appartement/paris-10eme-75/143940829.htm?p=',
                     u'photos': [u'https://v.seloger.com/s/width/800/visuels/0/3/k/e/03keicj7xdkyh7u68432p8wtqqn7d6kjr0p3whfcw.jpg',
                                 u'https://v.seloger.com/s/height/800/visuels/0/l/f/x/0lfxn0oodu5kejh0xd4a19th6jgnzqbr3ckklkpog.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/l/6/7/1l67fw2ifw69mt6n1zxc0dwn0qhhm7rjzxjgz1ukg.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/a/0/i/1a0ipj8wbcn9q1q2kjnjwr5u7z3ik22asf6zm53pc.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/1/q/b/5/1qb5ijfbe1x805zkfy2ufm4nxov0isi9ju7gsh5vk.jpg',
                                 u'https://v.seloger.com/s/width/800/visuels/2/4/c/s/24cs6yqjxqeuyveud1qpc01dc6rj507dz59x8jpj4.jpg',
                                 u'https://v.seloger.com/s/height/800/visuels/0/j/3/o/0j3oa53i3w6afvzadqg6mtwc1n14h3ck8kvekaku8.jpg'],
                     u'polygon': u'',
                     u'price': 292000.0,
                     u'priceAnnuity': 0.0,
                     u'priceUnit': u'\u20ac',
                     u'priceVariation': {u'date': u'0001-01-01T00:00:00',
                                         u'newPrice': 292000.0,
                                         u'oldPrice': 295000.0,
                                         u'status': 2},
                     u'professional': {u'directoryId': 61924,
                                       u'email': u'hulot.vincent@nope.com',
                                       u'id': 53937,
                                       u'logoUrl': u'https://v.seloger.com/s/width/75/logos/0/u/z/8/0uz8t56oxws9wugvne770pu7114hs90p0ppgs63rx.jpg',
                                       u'name': u'VILLAGE VOLTAIRE',
                                       u'phoneNumber': u'000000000',
                                       u'publicationId': 264655,
                                       u'type': 1},
                     u'publicationId': 264655,
                     u'realtyType': 1,
                     u'rooms': 2,
                     u'thirdPartyId': 48358,
                     u'title': u'Appartement',
                     u'transactionType': 2,
                     u'zipCode': u'75010'}],
         u'pageCount': 0,
         u'pageIndex': 0,
         u'pageSize': 50000,
         u'totalCount': 2}


DETAILS_SELOGER =  {u'alur': {u'feesPercentage': 3.96,
                   u'price': 249500.0,
                   u'priceExcludingFees': 240000.0,
                   u'textTemplate': 1},
         u'bedrooms': 1,
         u'city': u'Paris 10\xe8me',
         u'condoAnnualCharges': 0.0,
         u'condoProperties': 0,
         u'coordinates': {u'accuracy': 4,
                          u'latitude': 48.88185,
                          u'longitude': 2.36586},
         u'created': u'2019-04-03T11:11:00',
         u'dailyLife': {u'categories': [{u'category': 1,
                                         u'distance': 158,
                                         u'latitude': 48.88247299194336,
                                         u'longitude': 2.363913059234619,
                                         u'name': u'Ecole Primaire',
                                         u'type': 32},
                                        {u'category': 1,
                                         u'distance': 158,
                                         u'latitude': 48.88247299194336,
                                         u'longitude': 2.363913059234619,
                                         u'name': u'Ecole Maternelle Aqueduc',
                                         u'type': 31},
                                        {u'category': 1,
                                         u'distance': 163,
                                         u'latitude': 48.88330078125,
                                         u'longitude': 2.365530014038086,
                                         u'name': u'Halte Municipale Aqueduc',
                                         u'type': 43},
                                        {u'category': 1,
                                         u'distance': 187,
                                         u'latitude': 48.88158416748047,
                                         u'longitude': 2.3683841228485107,
                                         u'name': u'Coll\xe8ge Valmy',
                                         u'type': 30},
                                        {u'category': 2,
                                         u'distance': 3,
                                         u'latitude': 48.88184356689453,
                                         u'longitude': 2.3659098148345947,
                                         u'name': u'Yamadori ',
                                         u'type': 19},
                                        {u'category': 2,
                                         u'distance': 25,
                                         u'latitude': 48.88162612915039,
                                         u'longitude': 2.3658230304718018,
                                         u'name': u'Dia Paris Lafayette',
                                         u'type': 22},
                                        {u'category': 2,
                                         u'distance': 29,
                                         u'latitude': 48.881591796875,
                                         u'longitude': 2.3659250736236572,
                                         u'name': u'Franprix Paris',
                                         u'type': 21},
                                        {u'category': 2,
                                         u'distance': 43,
                                         u'latitude': 48.88152313232422,
                                         u'longitude': 2.3655240535736084,
                                         u'name': u'Espace Sud-Ouest ',
                                         u'type': 15},
                                        {u'category': 3,
                                         u'distance': 78,
                                         u'latitude': 48.88140106201172,
                                         u'longitude': 2.36503005027771,
                                         u'name': u'Pharmacie',
                                         u'type': 39},
                                        {u'category': 3,
                                         u'distance': 81,
                                         u'latitude': 48.88243865966797,
                                         u'longitude': 2.3665125370025635,
                                         u'name': u'Orthop\xe9die dento-faciale (Chirurgien-dentiste sp\xe9cialiste en orthop\xe9die dento-faciale)',
                                         u'type': 41},
                                        {u'category': 3,
                                         u'distance': 146,
                                         u'latitude': 48.88309097290039,
                                         u'longitude': 2.365189552307129,
                                         u'name': u'M\xe9decin g\xe9n\xe9raliste',
                                         u'type': 40},
                                        {u'category': 3,
                                         u'distance': 166,
                                         u'latitude': 48.88334655761719,
                                         u'longitude': 2.3657219409942627,
                                         u'name': u'PMI',
                                         u'type': 38},
                                        {u'category': 4,
                                         u'distance': 132,
                                         u'latitude': 48.88066482543945,
                                         u'longitude': 2.366023063659668,
                                         u'name': u'Commissariat central de police de Paris 10e arrondissement',
                                         u'type': 49},
                                        {u'category': 4,
                                         u'distance': 1194,
                                         u'latitude': 48.882747650146484,
                                         u'longitude': 2.382124423980713,
                                         u'name': u'Mairie du 19e arrondissement de Paris',
                                         u'type': 47},
                                        {u'category': 4,
                                         u'distance': 3398,
                                         u'latitude': 48.852020263671875,
                                         u'longitude': 2.3559014797210693,
                                         u'name': u'Brigade territoriale de proximit\xe9 de gendarmerie de La-Rivi\xe8re-Saint-Louis',
                                         u'type': 51},
                                        {u'category': 5,
                                         u'distance': 43,
                                         u'latitude': 48.881568908691406,
                                         u'longitude': 2.365448474884033,
                                         u'name': u'M\xe9tropolitain, station Louis-Blanc',
                                         u'type': 36},
                                        {u'category': 5,
                                         u'distance': 480,
                                         u'latitude': 48.877891540527344,
                                         u'longitude': 2.368499517440796,
                                         u'name': u'Festival international de la photographie de mode et de la beaut\xe9 (10e)',
                                         u'type': 80},
                                        {u'category': 5,
                                         u'distance': 576,
                                         u'latitude': 48.8841667175293,
                                         u'longitude': 2.3588173389434814,
                                         u'name': u'Bouffes du Nord-Centre international de cr\xe9ations th\xe9\xe2trales',
                                         u'type': 37},
                                        {u'category': 5,
                                         u'distance': 1642,
                                         u'latitude': 48.86922073364258,
                                         u'longitude': 2.377471923828125,
                                         u'name': u"Mus\xe9e Jeanne d'Arc",
                                         u'type': 79},
                                        {u'category': 6,
                                         u'distance': 184,
                                         u'latitude': 48.88325119018555,
                                         u'longitude': 2.3645100593566895,
                                         u'name': u'Gymnase Ch\xe2teau Landon',
                                         u'type': 26},
                                        {u'category': 6,
                                         u'distance': 200,
                                         u'latitude': 48.88325119018555,
                                         u'longitude': 2.364140033721924,
                                         u'name': u'Piscine Ch\xe2teau Landon',
                                         u'type': 71},
                                        {u'category': 6,
                                         u'distance': 210,
                                         u'latitude': 48.883270263671875,
                                         u'longitude': 2.363960027694702,
                                         u'name': u"Centre d'Animation Ch\xe2teau Landon",
                                         u'type': 29},
                                        {u'category': 6,
                                         u'distance': 210,
                                         u'latitude': 48.883270263671875,
                                         u'longitude': 2.363960027694702,
                                         u'name': u"Centre d'Animation Ch\xe2teau Landon",
                                         u'type': 61},
                                        {u'category': 7,
                                         u'distance': 71,
                                         u'latitude': 48.88126754760742,
                                         u'longitude': 2.36545729637146,
                                         u'name': u'Campanile Paris Gare du Nord (3 \xe9toiles)',
                                         u'type': 44},
                                        {u'category': 7,
                                         u'distance': 832,
                                         u'latitude': 48.876041412353516,
                                         u'longitude': 2.358687162399292,
                                         u'name': u'Camping Lou Passavous (3 \xe9toiles)',
                                         u'type': 45},
                                        {u'category': 7,
                                         u'distance': 1610,
                                         u'latitude': 48.88715744018555,
                                         u'longitude': 2.3863306045532227,
                                         u'name': u"Appart'City (2 \xe9toiles)",
                                         u'type': 46}],
                        u'summary': [{u'count': 88, u'type': 1},
                                     {u'count': 37, u'type': 2},
                                     {u'count': 30, u'type': 3},
                                     {u'count': 1, u'type': 4}]},
         u'description': u"Appartement vendu lou\xe9 - Rue du Faubourg Saint-Martin / Rue Lafayette. Au 2\xe8me et dernier \xe9tage d'un immeuble ancien bien tenu, 2 pi\xe8ces enti\xe8rement sur cour de 25,49m\xb2 carrez, compos\xe9 comme suit: Entr\xe9e, s\xe9jour de 15m\xb2, cuisine am\xe9ricaine, une chambre avec dressing, salle d'eau avec cabinet de toilette (broyeur). L'appartement est actuellement lou\xe9 au prix de 850 euros /mois + 50 euros de provisions sur charges. Bail non meubl\xe9 en date du 15/06/2017. Tanti\xe8mes (13/1000 \xe8mes). Charges de copropri\xe9t\xe9: 87 euros / mois - Taxe fonci\xe8re: 237 euros /an.",
         u'energy': {u'grade': u'F', u'status': 0, u'value': 341},
         u'features': [{u'category': 1, u'icon': 6, u'label': u'Vue'},
                       {u'category': 1,
                        u'icon': 11,
                        u'label': u'Orientation Est, Nord'},
                       {u'category': 2,
                        u'icon': 0,
                        u'label': u'Refait \xc0 Neuf'},
                       {u'category': 2,
                        u'icon': 0,
                        u'label': u'Surface de 25,49 m\xb2'},
                       {u'category': 2,
                        u'icon': 0,
                        u'label': u'Ann\xe9e de construction 1900'},
                       {u'category': 2,
                        u'icon': 0,
                        u'label': u'B\xe2timent de 2 \xe9tages'},
                       {u'category': 2,
                        u'icon': 0,
                        u'label': u'Au 2\xe8me \xe9tage'},
                       {u'category': 2,
                        u'icon': 0,
                        u'label': u'2 Pi\xe8ces'},
                       {u'category': 2, u'icon': 0, u'label': u'1 Chambre'},
                       {u'category': 3,
                        u'icon': 0,
                        u'label': u"1 Salle d'eau"},
                       {u'category': 3, u'icon': 0, u'label': u'1 Toilette'},
                       {u'category': 3, u'icon': 0, u'label': u'Parquet'},
                       {u'category': 3, u'icon': 0, u'label': u'Rangements'},
                       {u'category': 3,
                        u'icon': 0,
                        u'label': u'T\xe9l\xe9vision Par C\xe2ble'},
                       {u'category': 3,
                        u'icon': 0,
                        u'label': u'Chauffage individuel \xe9lectrique radiateur'},
                       {u'category': 3,
                        u'icon': 0,
                        u'label': u'Cuisine am\xe9ricaine'},
                       {u'category': 3, u'icon': 0, u'label': u'Entr\xe9e'},
                       {u'category': 3, u'icon': 0, u'label': u'S\xe9jour'},
                       {u'category': 3,
                        u'icon': 0,
                        u'label': u'S\xe9jour de 14 m\xb2'},
                       {u'category': 5,
                        u'icon': 0,
                        u'label': u'Situation ville'},
                       {u'category': 5, u'icon': 0, u'label': u'Interphone'},
                       {u'category': 5, u'icon': 0, u'label': u'Digicode'},
                       {u'category': 5, u'icon': 0, u'label': u'Calme'}],
         u'greenhouseGas': {u'grade': u'C', u'status': 0, u'value': 11},
         u'id': 145738991,
         u'isExclusiveness': True,
         u'isIndividual': False,
         u'isSelection': False,
         u'lastModified': u'2019-04-03T11:20:00',
         u'level': 1,
         u'livingArea': 25.49,
         u'livingAreaUnit': u'm\xb2',
         u'permalink': u'https://www.seloger.com/annonces/achat/appartement/paris-10eme-75/louis-blanc-aqueduc/145738991.htm?p=',
         u'photos': [u'https://v.seloger.com/s/width/800/visuels/1/f/v/j/1fvjvbww58zscnf45rbucw73jy711bc6n1aoc1q38.jpg',
                     u'https://v.seloger.com/s/width/800/visuels/1/y/0/h/1y0h26gluxdonvjjxk2mfv18bdrn5s1c0715g8cpg.jpg',
                     u'https://v.seloger.com/s/width/800/visuels/2/6/1/5/2615zgt53fhyjvko92d2swp6hn50485ua4e2u5mc4.jpg',
                     u'https://v.seloger.com/s/width/800/visuels/0/h/n/a/0hna00i5kocz640c7nqz0u9ed7vpg1e580021if6c.jpg',
                     u'https://v.seloger.com/s/width/800/visuels/0/n/1/4/0n14emm1udnwf0u6ml985mo73gmozayrvpzvnpnis.jpg',
                     u'https://v.seloger.com/s/cdn/x/visuels/0/r/1/r/0r1r9r8fvyuf270uapsc5m7c2tt8wz7y27zwhdvrx.jpg'],
         u'polygon': u'',
         u'price': 249500.0,
         u'priceAnnuity': 0.0,
         u'priceDescription': u"* Prix net, hors frais notari\xe9s, d'enregistrement et de publicit\xe9 fonci\xe8re",
         u'priceUnit': u'\u20ac',
         u'priceVariations': [],
         u'professionals': [{u'address': u'112 boulevard de Rochechouart  \n75018 Paris 18\xe8me',
                             u'directoryId': 66479,
                             u'email': u'contact@nope.com',
                             u'id': 73906,
                             u'latitude': 48.8822556,
                             u'level': 3,
                             u'logoUrl': u'https://v.seloger.com/s/height/75/logos/1/f/1/h/1f1h2vluc6txzkajusbg4rwbm00mivs35sc8konk5.jpg',
                             u'longitude': 2.340066,
                             u'name': u'AGENCE SAP',
                             u'phoneNumber': u'00000000000000',
                             u'publicationId': 390615,
                             u'type': 1,
                             u'url': u'https://www.seloger.com/professionnels/agences-immobilieres/paris-18eme-75/agency-66479.htm'}],
         u'publicationId': 390615,
         u'realtyType': 1,
         u'reference': u'FSM',
         u'rooms': 2,
         u'schools': [{u'address': u'',
                       u'city': u'',
                       u'isAvailable': False,
                       u'latitude': 0.0,
                       u'longitude': 0.0,
                       u'name': u'',
                       u'type': 4,
                       u'zipCode': u''},
                      {u'address': u'199 quai de Valmy',
                       u'city': u'Paris',
                       u'isAvailable': True,
                       u'latitude': 48.8815842,
                       u'longitude': 2.36838412,
                       u'name': u'Coll\xe8ge Valmy',
                       u'type': 3,
                       u'zipCode': u'75010'},
                      {u'address': u'',
                       u'city': u'',
                       u'isAvailable': False,
                       u'latitude': 0.0,
                       u'longitude': 0.0,
                       u'name': u'',
                       u'type': 2,
                       u'zipCode': u''},
                      {u'address': u"39 Rue de l'Aqueduc",
                       u'city': u'Paris',
                       u'isAvailable': True,
                       u'latitude': 48.882473,
                       u'longitude': 2.363913,
                       u'name': u'Ecole Maternelle Aqueduc',
                       u'type': 1,
                       u'zipCode': u'75010'}],
         u'thirdPartyId': 102753,
         u'title': u'Appartement',
         u'transactionType': 2,
         u'transportations': {u'available': [{u'count': 10,
                                              u'distance': 52,
                                              u'latitude': 48.88140106201172,
                                              u'lines': u'2,4,5,7,7B',
                                              u'longitude': 2.3656299114227295,
                                              u'name': u'Louis Blanc',
                                              u'type': 3},
                                             {u'count': 89,
                                              u'distance': 65,
                                              u'latitude': 48.88151168823242,
                                              u'lines': u'26,30,31,32,35,38,39,42,43,46,47,48,54,56,65,75,302,350,519',
                                              u'longitude': 2.3651347160339355,
                                              u'name': u'Louis Blanc',
                                              u'type': 1},
                                             {u'count': 48,
                                              u'distance': 164,
                                              u'latitude': 48.881996154785156,
                                              u'lines': u'',
                                              u'longitude': 2.3636252880096436,
                                              u'name': u"V\xe9lib' - Aqueduc",
                                              u'type': 11},
                                             {u'count': 5,
                                              u'distance': 573,
                                              u'latitude': 48.88033676147461,
                                              u'lines': u'',
                                              u'longitude': 2.358372211456299,
                                              u'name': u'Magenta',
                                              u'type': 2},
                                             {u'count': 3,
                                              u'distance': 611,
                                              u'latitude': 48.880001068115234,
                                              u'lines': u'B,D,E,H,K,P',
                                              u'longitude': 2.357990026473999,
                                              u'name': u'Gare du Nord Magenta',
                                              u'type': 14}],
                              u'metadata': [{u'color': u'df9ab1',
                                             u'name': u'7',
                                             u'type': 3},
                                            {u'color': u'79bb92',
                                             u'name': u'7b',
                                             u'type': 3},
                                            {u'color': u'216eb4',
                                             u'name': u'2',
                                             u'type': 3},
                                            {u'color': u'de8b53',
                                             u'name': u'5',
                                             u'type': 3},
                                            {u'color': u'bb4d98',
                                             u'name': u'4',
                                             u'type': 3},
                                            {u'color': u'bd76a1',
                                             u'name': u'E',
                                             u'type': 14},
                                            {u'color': u'f0b600',
                                             u'name': u'P',
                                             u'type': 14},
                                            {u'color': u'427dbd',
                                             u'name': u'B',
                                             u'type': 14},
                                            {u'color': u'5e9620',
                                             u'name': u'D',
                                             u'type': 14},
                                            {u'color': u'7b4339',
                                             u'name': u'H',
                                             u'type': 14},
                                            {u'color': u'c7b300',
                                             u'name': u'K',
                                             u'type': 14}],
                              u'nearest': {u'count': 1,
                                           u'distance': 51,
                                           u'latitude': 48.882015228271484,
                                           u'lines': u'54',
                                           u'longitude': 2.3665249347686768,
                                           u'name': u'Louis Blanc',
                                           u'type': 1}},
         u'zipCode': u'75010'},
 'room': 2,
  'source': 'SeLoger',                                                                                                                                                     'surface': 25.49,
 'surface_unit': u'm\xb2'}

